### Global variables ###
OWNER_NAME = "watchful1"
ACCOUNT_NAME = "UpdateMeBot"
USER_AGENT = "UpdatedMe/Subscribe (by /u/"+OWNER_NAME+")"
SLEEP_TIME = 60*3
WARNING_RUN_TIME = 60*2
COMMENT_EDIT_DAYS_CUTOFF = 30
COMMENT_EDIT_ITERATIONS = 5
BACKUP_ITERATIONS = 100
DATABASE_NAME = "database.db"
LOGFOLDER_NAME = "logs"
BACKUPFOLDER_NAME = "backup"
MAX_MULTIREDDIT_SIZE = 10

SUBSCRIPTION_NAME = "subscribeme"
UPDATE_NAME = "updateme"
