name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Test with pytest
      run: |
        export PATH=/home/runner/.local/bin:$PATH
        pip install --user pipenv
        pipenv install --dev
        pipenv run pytest
